disable_ray: false
max_tokens: 4096
models:
- meta-llama/Llama-2-7b-hf
num_gpus: 8
num_tensor_parallel_workers:
- 1
- 2
- 4
- 8
output_dir: /workspace/Vidur/profiling_outputs/Llama-2-7B/mlp/2025-03-18_02-37-16
profile_method: record_function
